version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    env_file: postgres_secrets.env
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: postgres_secrets.env
    ports:
      - "6060:80"
volumes:
  db:
    driver: local
