version: "3.8"

services:
  db:
    image: surrealdb/surrealdb:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - db:/sdb_data
    command: start --user ${SURREAL_USER} --pass ${SURREAL_PASS} file:sdb_data/database.db
    env_file: surreal_secrets.env
volumes:
  db:
    driver: local
