version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    env_file: mongo_secrets.env
    ports:
      - 27018:27017
    volumes:
      - ~/mongo/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 50235:8081
    env_file: mongo_secrets.env
